### ISSUE TITLE
Add many-body SASA energy

### ISSUE THREAD

**Issue by mlund** [mlund/faunus#101]
`Energy::Hamiltonian` is now exposed to python, see

https://github.com/mlund/faunus/blob/master/examples/pythontest.py

At the end of the script, SASA energies are calculated using a pair-potential and PowerSASA, respectively. As it’s just two particles, the two methods should return identical energies, which they do, except at long distances, where PowerSASA misbehaves. The pair-potential uses mixing rules for atomic `tfe` and `tension` which will need to be discussed further.
The bug seems to be sporatic; running the test several times, the correct value occasionally appears.

Interesting links about SASA calc.:
- [FreeSASA, C library](https://freesasa.github.io/doxygen/Geometry.html)
- C++ code: https://github.com/nioroso-x3/dr_sasa_n
- more code: https://www.cgl.ucsf.edu/chimera/data/sasa-nov2013/sasa.html
- c++ code: https://github.com/atfrank/PCASA
- [review of methods](https://www.researchgate.net/profile/Md_Hassan3/publication/261217248_A_Review_of_Methods_Available_to_Estimate_Solvent-Accessible_Surface_Areas_of_Soluble_Proteins_in_the_Folded_and_Unfolded_States/links/02e7e536c94945fa72000000.pdf)

**Comment by mlund** [comment]
ping @rc83

**Comment by rc83** [comment]
FreeSASA binding is now implemented in Faunus without optimizations and excessive testing (#189, c4ecc5f, 5e1cfe8), passing the unit tests, albeit only within 3% numerical accuracy. This issue will be now repurposed to track the progress of SASA implementation until the next release.

**Comment by mlund** [comment]
Can this be closed? @rc83

**Comment by mlund** [comment]
Should this be postponed to Version 2.4.0?

For PBC and non-polymeric molecules, could we use a cutoff to calculate sasa change for a single molecule translation or rotation?
