### ISSUE TITLE
default nonbonded scheme

### ISSUE THREAD

**Issue by mlund** [mlund/faunus#147]
Since it's more stable and works for all pair-potentials (incl. anisotropic), the default nonbonded scheme should be `FunctorPotential`. To keep backwards compatibility, we could define the following:

 keyword    |  class
:---------- | :-------------
`nonbonded` | `FunctorPotential`
`nondonded_exact` | `FunctorPotential`
`nonbonded_splined` | `TabulatedPotential`

OK?

ping @gitesei @rc83

**Comment by rc83** [comment]
I agree. And to be professional ;-), I would put a sentence into the documentation that using the `nonbonded` keyword is recommended, however the exact implementation behind may be changed in the future.
