### ISSUE TITLE
Documentation of new potentials

### ISSUE THREAD

**Issue by mlund** [mlund/faunus#156]
Document the use of the following potentials (in topology.md, energy.md):

- [x] squarewell (a8f7ae597ad2ceb72fb80eafaed91b4a72ff3e95). `sigma_sw` is not a good as it would suggest that it's a diameter but is interpreted as a radius. Perhaps `threshold_sw`?
- [x] hertz (a00834b9c5b7df079d9ebdd156b74118411fe5bc)
- [ ] dipoledipole (782c284318508117ef0f8c2335cd80a0d550fb97)
- [ ] stockmayer (782c284318508117ef0f8c2335cd80a0d550fb97)

Ping @bjornstenqvist

**Comment by bjornstenqvist** [comment]
Since we do not have stockmayer anymore, is not this issue solved not?

**Comment by bjornstenqvist** [comment]
*now

**Comment by mlund** [comment]
Oh yes
