### ISSUE TITLE
Excluded neighbors in non-bonded interaction 

### ISSUE THREAD

**Issue by rc83** [mlund/faunus#161]
The Hamiltonian of many force fields does not include a non-bonded energy between particles which are connected by a bond (1-2 interaction). Furthermore, this can be also extended to 1-3 and 1-4 interactions where the mutual interaction energy is already fully determined by the angular and dihedral potentials, respectively.

Therefore the specification of particle pairs with excluded non-bonded energy should be permitted in the topology. Only particle pairs within a single molecule are allowed. Beside an explicit configuration option, convenient shortcuts can be also provided, e.g., an extra attribute of the bonded interaction.

Subtraction of the non-bonded energy is perhaps a good implementation strategy, accounting for the performance. However a special attention has to be paid for high or even infinite energy values, e.g., overlapping hard spheres (the sphere diameter is greater than the bond length). Van der Waals interaction and electrostatics should be handled independently internally.

The implementation can also account for a 1-4 pair interaction, i.e., a bonded potential in a form of the scaled non-bonded potential.

**Comment by mlund** [comment]
Is it reasonable that `MoleculeData` holds this information? In that case, the `g_internal()` energy function of non-bonded would need to account for this.

**Comment by rc83** [comment]
`MoleculeData` is a good structure to contain this additional topology information. I believe the implementation should be straightforward, if the non-bonded energy between two particles is readily available to subtract it. Only the high/infinite energies will require some extra treatment.

**Comment by mlund** [comment]
if `MoleculeData` contains a recipe for calculating the internal energy, there's no need to subtract. It could be a list of particle pairs similar the structure in bonded interactions.

**Comment by rc83** [comment]
It is more complicated as the definition of pairs involved in the ordinary non-bonded interaction is negative, i.e., compute everywhere if not excluded. The positive definition, i.e., state all pairs explicitly in list, is not feasible for larger molecules as it scales O(N²) and only a fraction of pairs would be  excluded. Furthermore, faunus distinguish only between bonded and non-bonded energy, not intra- and intermolecular energy. 

The computations of bonded energy, that also includes possible 1-4 scaled interaction, is straightforward. The computation of the non-bonded energy now takes all particles, finds the interaction parameters based on the particle types, and accumulates the energy. If exclusions are involved, the exclusion has to be checked for each pair which may cause some penalty and affect the performance. Hence a smarter way is welcome.

Another notice: Excluded neighbours have to be treated with care in Ewald summation to distinguish between interactions within the molecule and between its replicas.

**Comment by mlund** [comment]
How about a bitfield (NxN matrix) where each value (default to 1) is always multiplied with the non-bonded interaction energy for the i,j pair. Memory efficient, unconditional, and simple to implement.

**Comment by mlund** [comment]
A bit more info on bits: 
- https://stackoverflow.com/questions/3806469/bit-array-in-c

**Comment by rc83** [comment]
The bitmap should work nicely for up to moderately big systems. Hence I suggest: 
1. no exclusions in the system at all handled by an if-condition
2. a bit map for the moderately big systems
3. as previous but a warning should be emitted

**Comment by rc83** [comment]
Naïve implementation of exclusions using bit map (actually a char map for now) is done. However, the memory footprint can be optimized for some common molecules. In linear (CG) molecules the distance between indices of excluded neighbours is very limited (_m_ ≲ 4), hence memory complexity is greatly reduced (_m_ × _n_ ≪ _n_ × _n_), as anything farther than _m_ is not excluded by a direct condition.

- [ ]  _m_ × _n_ version of exclusion bitmap
- [ ] emit warnings if the bitmap is too big
- [ ] add a new option `exclude_nb = n` which will automatically append the exclusion list based on the bonded distance `n` in the molecule

**Comment by rc83** [comment]
Implemented and tested. Before polishing and documenting we should decide how the JSON structures should look like.

1. How shall be named the keyword to exclude non-bonded interactions among neighbours within a given distance?
2. How shall be named the array of exclusions? `exclusionlist`?
3. Is a simple array, i.e., `[[i, j], …]`, good enough structure? Will be future extension possible to incorporate using this format? For example, to discriminate electrostatics and van der Walls interactions.

**Comment by rc83** [comment]
Closed by #211.
