### ISSUE TITLE
Inserting single ion for individual activity coefficient - bug

### ISSUE THREAD

**Issue by kubawlo** [mlund/faunus#165]
The program produces the following errors while trying to simulate a _single ion_ insertion using the Widom sampling method (input file in .txt attached - to be converted to .json):
[in_widom_single.txt](https://github.com/mlund/faunus/files/3364851/in_widom_single.txt)

`
[json.exception.type_error.316] invalid UTF-8 byte at index 25: 0x91`

**or**

 ```
faunus(52245,0x11173b5c0) malloc: Incorrect checksum for freed object 0x7fc6d8600048: probably modified after being freed.
Corrupt value: 0x40500db6597a4841
faunus(52245,0x11173b5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**or, if it happens to execute to 100%**

`segmentation fault: 11`

**Comment by mlund** [comment]
This bug should already be fixed in the master branch. Could you report your version/commit hash? (i.e. run `faunus --version`). To get the latest updates, download and compile from source by following the instructions [here](https://faunus.readthedocs.io/en/latest/_docs/install.html). Please report back if this works, or if not, an input file that reproduces the error.

**Comment by kubawlo** [comment]
I followed the update commands from the manual
```
faunus --version    
conda search faunus 
conda upgrade faunus
```
And successfully installed version 
`faunus                    2.2.0            py37h88e9a90_0    conda-forge`


Unfortunately, when I run [this input file](https://github.com/mlund/faunus/files/3365123/input-single.txt) (in the .yml format) I get error messages
```
faunus(72280,0x115a2e5c0) malloc: Incorrect checksum for freed object 0x7fc4af300048: probably modified after being freed.
Corrupt value: 0xc011dc4995d02830
faunus(72280,0x115a2e5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
``` 
or
```
Segmentation fault: 11                                                 ] 0% 0s
```

The error seems to appear inconsistently, i.e. sometimes the program manages to run a few tenths of % before crashing.
The program does work fine with ionic pair insertion:
```insertmolecules:
    - HBr: {N: {{ N }}}
    - HBr: {N: 1, inactive: true}
```
and 
```
analysis:
    - systemenergy: {file: energy.dat, nstep: 100}
    - savestate: {file: confout.pqr}
    - savestate: {file: state.json}
    - widom: {molecule: HBr, ninsert: 100, nstep: 5}
```
I am working on macOS Mojave v. 10.14.5

**Comment by mlund** [comment]
The bugfix will be included in the next release but is currently not available as a binary via anaconda. You need to compile from _source_. As you already have anaconda installed, you can use the provided `scripts/environment.yml` file to install dependencies required for a build,

~~~ bash
git clone http://github.com/mlund/faunus
cd faunus
conda env create -f scripts/environment.yml
source activate faunusdev
cmake .
make faunus
~~~

**Comment by kubawlo** [comment]
Great, I tested it and single ion insertion is working without errors - thank you. I will compare the model with experiments (first using mean activity coefficients).
