### ISSUE TITLE
Unknown property eps

### ISSUE THREAD

**Issue by rc83** [mlund/faunus#183]
The test fails showing an error message indicating that `eps` value is not set. The error occurrence depends on the build environment. I am not able to reproduce it in my Linux system using either gcc 8.3 or clang 7.1 and also travis passes without issues.

The error has appeared in Giulio's @gitesei system (MacOS with clang) so far. It stems from the copy assignment `json j_remaining_properties = val;` in `atomdata.cpp`. The new json object is not iterated as a json-object but as a json-array instead, i.e., the keys become numeric indices instead of attribute names. I did not find any indication for such behaviour in the nlohmann json library documentation.

Nest step: Learn more about Giulio's system, e.g., clang version.

**Comment by rc83** [comment]
Giulio uses clang 10. However I am not able to reproduce the bug using clang 10.0 on my Linux machine.

The following workaround works for Giulio. 
```//json j_remaining_properties = val;
json j_remaining_properties = json::parse(val.dump());
```
Mikael @mlund, how should be this issue resolved?

**Comment by mlund** [comment]
Can this be boiled down to a simple example that reproduces the issue? We could post to the nlohmann/json issue tracker.

**Comment by rc83** [comment]
I have prepared a simple example which may fail in a similar way. Waiting for @gitesei (via slack) to test it as nothing fails in my environment. Mikael, does `make test` work for you on mac?

**Comment by mlund** [comment]
Yes, all 17 tests in c4ecc5fe5e0f1bbe6f09eb11991a00cffd265650 pass using xcode compiler:
~~~
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
~~~

**Comment by rc83** [comment]
Thanks! Let's wait for Giulio then. So far he is the only one experiencing this issue hence it could be related to his specific environment or setup. I would not consider this issue as a blocker of 2.3 version.

**Comment by mlund** [comment]
@MarcoPolimeni had the same issue this week; he and @gitesei both use macports which I don't. The issue appered also with GCC.

**Comment by gitesei** [comment]
With the latest Faunus and the workaround in `atomdata.cpp`, `chain` and `cluster` tests are now failing on my laptop.
`chain` and `cluster` fail because of `√⟨r_cm²⟩  0.348 vs. 0.51` and `⟨N⟩ 3.5 vs. 3.99` but they don't return any errors or warnings.
I uninstalled macports (https://guide.macports.org/chunked/installing.macports.uninstalling.html) and installed cmake with brew but that unfortunately didn't help.

**Comment by rc83** [comment]
1. If you place the following static assertion in `potentials.h`, does it fail during compilation? (Perhaps not, but that will let us exclude the obvious reason.) ``static_assert(NLOHMANN_JSON_VERSION_MAJOR == 3 && NLOHMANN_JSON_VERSION_MINOR == 5, "nlohmann/json == 3.5 required.");``

2. The chain example is butchered anyway as I discovered last week. It shall contain `"default" : ["hardsphere": {}]` instead of `"default" : ["hardsphere"]`. I will make a fix. The cluster example is even more mysterious in my system: The test passes. However if I compare its output by hand, i.e.,  `../../scripts/jsoncompare.py cluster.out.json out.json`, I have three failing values (bias rejection rate, ⟨N⟩, acceptance).

**Comment by gitesei** [comment]
The issue gets solved by compiling Faunus within a conda environment with the packages clang_osx-64 and clangxx_osx-64

**Comment by rc83** [comment]
This suggests a non-sane build environment. However the exact reason is difficult to determine. As a reliable way to build Faunus exists on the affected Macs now, I think that the issue can be closed.
CC @MarcoPolimeni
