### ISSUE TITLE
JSON input validation

### ISSUE THREAD

**Issue by rc83** [mlund/faunus#198]
Faunus heavily rely on configuration provided by a user in JSON file. However the JSON configuration is not validated at all, hence unknown properties may be silently ignored. This can happen for example by typo in optional parameter or using newer configuration with older version of Faunus.

To mitigate this issue, in some parts of the code `SingleUseJSON` class used which removes its content, a key by key when it is asked for the given key. This is less than optimal as it breaks `const json&` semantic when construction of compounded objects is involved.

Using the JSON schema validation can resolve this issue. There is a [C++ library](https://github.com/pboettch/json-schema-validator), based on JSON for Modern C++ library already used by Faunus, which can be employed. Writing a schema is pretty straightforward. Hence this can be a way to go.

**Comment by mlund** [comment]
An alternative is to use a python scema library and let `yason.py` handle the validation.

**Comment by mlund** [comment]
Schemas can be used to construct forms for input: https://jsonforms.io
