### ISSUE TITLE
GCMC and Coulomb

### ISSUE THREAD

**Issue by mlund** [mlund/faunus#226]
Adding a coulomb term to the WCA pair-potential, i.e. `- coulomb: {type: plain, epsr: 80}`
the `sodiumphosphate/` example encounters a particle-particle distance of _exactly_ zero, which triggers an assertion error in CoulombGalore. The problem doesn't happen if starting from the test restart file. I have confirmed that this happens also on a simple GCMC salt system.

ping @gitesei @rc83

**Comment by mlund** [comment]
The issue shows up when two particles are added to the `change` object and happens to have exact same positions. Why would they have identical positions (it's not the same particle). Are new positions assigned to particles in the reservoir? `Randominserted`? @gitesei do you recall some of this from the lipid GC move?

**Comment by rc83** [comment]
The positions when inserting shall be randomized, indeed. However, the exactly zero distance can theoretically appear upon a trial move anytime during the simulation. Hence such a situation shall be gracefully handled by the (combined) potentials in Faunus. The most tricky case is perhaps summation of minus and plus infinity, e.g., oppositely charged hard spheres.

**Comment by mlund** [comment]
For a temporary fix, see 5e482f8. It does not solve the origin of the problem but allow to equilibrate whereafter r=0 doesn't happen.

**Comment by mlund** [comment]
Accidentally throwing an identical vector of three doubles twice is for all practical purposes impossible. It's more likely a bug and it seems very small distances are being generated several times. When the system has equilibrated it doesn't seem to happen again.
