### ISSUE TITLE
[question] Read position from xyz file 

### ISSUE THREAD

**Issue by ohyh** [mlund/faunus#268]
Dear Faunus team,

I appreciate for your efforts on building a wonderful package. It is very useful for my research. 

I have questions about atomic: true or false. **Q1.** If I want to insert a molecule that contains only one atom, just like noble gas molecule, atomic should be always true?
  
I have xyz file that contains desired spatial distribution of single-atom molecules. In the `insertmolecue` section, it seems like {position:test.xyz} option is not working for molecules that {atomic: true}. Read position information from test.xyz is perfectly fine for molecules that {atomic: false}. **Q2.** Is it forbidden for inserting {atomic: true} molecules by reading positions from xyz file?

Thanks for your time and effort.

Sincerely,
A user

**Comment by mlund** [comment]
1. False. The `atomic` keyword is an optimization for a collection or atoms that are not tied up with bonds, nor rigid. We used it for salt particles, or as you describe a noble gas. But it you want to insert multiple molecules with only one atom and `atomic=False`, that is perfectly fine.

2. True. When detecting the `atomic` keyword, the `structure` field is currently ignored in the `moleculelist`. However there's no reason why we couldn't read user-defined positions also for `atomic` groups. Let's ping @rc83 and see if he has a suggestion for where to best fix this.

PS: Thanks for the kind words!

**Comment by rc83** [comment]
I would separate the issue in two distinct ones.

1. Do atomic molecules have a structure? Though it is not common in a usual simulation setup, they actually could have one, e.g., a crystal lattice of a solid salt. However, Faunus does not support this at the moment. 

2. Should it be possible to place molecules (and atoms in the atomic ones) at positions specified in a configuration? Definitely! Faunus is even prepared for that. However currently `RandomInserter` is the only implementation of abstract `MoleculeInserter`, which directs the molecule placement. I will create an issue to implement another `MoleculeInserter` which places molecules at coordinates provided in a file. This should solve your issue. I am hesitate to promise the exact Faunus release which will contain this feature but let's hope for the next one. ;)

As a side note, a system state (including positions of all particles) can be stored in a state file during the simulation, which may be then re-used to restart the simulation, e.g., `faunus -i input.json -s state.init.json`. The coordinates of particles in the state file can be changed using a script. But this is a plain hacking on your own risk.

**Comment by mlund** [comment]
Until the above is implemented, modifying the state file as @rc83 proposed is likely the easiest way to solve your immediate use-case. The state file is json and is easily handled by Python as described [here](https://faunus.readthedocs.io/en/latest/_docs/running.html#post-processing).

**Comment by ohyh** [comment]
Dear rc83 and mlund,

I appreciate for super-fast and kind answers. 

I think all my questions are resolved except for a minor one. I'm a little bit confused by following message. 
> However currently `RandomInserter` is the only implementation of abstract `MoleculeInserter`, which directs the molecule placement."
In "Initial Configuration" section of the manual, under `insertmolecules` module, there is a option `positions` says "Load positions from file (aam, per, xyz)". Are you saying that the option is not implemented to the package yet? I'm confused because the manual says there is the function that I wanted to use. 

Again, thanks for your efforts.

**Comment by rc83** [comment]
It does work but perhaps not exactly how you expect. Let me explain in detail. 

1. The attribute `positions` of `insertmolecules` works only for molecules which are not atomic. 2. The most tricky part here is, that the file given in `positions` has to be a trajectory (not a single static frame) and each frame must contain exactly one molecule placed at particular position. The molecule's positions are read frame by frame. However, the positions are only permissible positions for insertion which `RandomInserter` randomly chooses from when it actually inserts the molecule into the simulation box. 3. The molecule's `keeppos` attribute must be set to `true`.

Cumbersome, isn't it? I suspect that this feature was quickly added some time ago upon an urgent request of our colleague. Nevertheless, I consider the ability to explicitly direct initial molecule placement as an important feature and I am prioritizing its proper implementation. Thank you for pointing out that this feature is missing. Meanwhile I would recommend to adjust the state file as the safest way to go.
