### ISSUE TITLE
Request additional functionality on `customexternal`

### ISSUE THREAD

**Issue by ohyh** [mlund/faunus#272]
As mentioned in following discussions, I'd like to request an additional functionality on `customexternal`. It would be great if I could apply `customexternal` to certain atom type specifically, other than apply it on the whole molecule. 

> Right, this is currently not supported but a good idea. The attached patch will allow you to access `id` (particle id) in the expression and use it with a conditional. Please test it and if it works for you, consider making a pull request so that we can add it to the master branch. To apply the patch, save the snippet to a file and run `git apply {patchfile}` in the main faunus directory.

``` diff
diff --git a/src/externalpotential.cpp b/src/externalpotential.cpp
index c8397e02..00b5c40f 100644
--- a/src/externalpotential.cpp
+++ b/src/externalpotential.cpp
@@ -333,14 +333,17 @@ CustomExternal::CustomExternal(const json &j, Space &spc) : ExternalPotential(j,
         constants["Nav"] = pc::Nav;
         constants["T"] = pc::temperature;
         expr = std::make_unique<ExprFunction<double>>();
-        expr->set(
-            j,
-            {{"q", &particle_data.charge}, {"x", &particle_data.x}, {"y", &particle_data.y}, {"z", &particle_data.z}});
+        expr->set(j, {{"q", &particle_data.charge},
+                      {"x", &particle_data.x},
+                      {"y", &particle_data.y},
+                      {"z", &particle_data.z},
+                      {"id", &particle_data.id}});
         func = [&](const Particle &a) {
             particle_data.x = a.pos.x();
             particle_data.y = a.pos.y();
             particle_data.z = a.pos.z();
             particle_data.charge = a.charge;
+            particle_data.id = a.id;
             return expr->operator()();
         };
     }
diff --git a/src/externalpotential.h b/src/externalpotential.h
index 57c1fc97..1a030403 100644
--- a/src/externalpotential.h
+++ b/src/externalpotential.h
@@ -83,7 +83,7 @@ class CustomExternal : public ExternalPotential {
   private:
     std::unique_ptr<ExprFunction<double>> expr;
     struct ParticleData { // storage for particle properties
-        double charge = 0, x = 0, y = 0, z = 0;
+        double charge = 0, x = 0, y = 0, z = 0, id = -1;
     };
     ParticleData particle_data;
     json json_input_backup; // initial json input
```

_Originally posted by @mlund in https://github.com/mlund/faunus/issues/269#issuecomment-618196433_

**Comment by ohyh** [comment]
I tried to post it on Pull request.. And I even fail to delete this issue. Git Hub is quite new to me. Sorry for confusion.

**Comment by ohyh** [comment]
I tried to post it on Pull request... I learn from search that I should edit the code for making Pull request. Would it be possible for you to delete this issue? Sorry for the confusion.

**Comment by mlund** [comment]
To make a Pull Request (PR), you can _fork_ faunus on the github homepage. You then download your fork, make changes to it, and _push_ the changes up to github with (`git push`). Once it's online we can make a PR from your fork into the main Faunus repository. You can read more [here](https://help.github.com/en/github/getting-started-with-github/fork-a-repo).

**Comment by mlund** [comment]
Any luck forking the master branch?

**Comment by ohyh** [comment]
Actually, I failed to compile Faunus from source code and currently using 2.3.0 that installed via Conda. Thanks to your idea in #273, I built my ratchet system successfully. So, at this time, I'm fine without the patch. I appreciate your help to resolve my issues.

**Comment by mlund** [comment]
OK, I'll close now -- feel free to re-open if needed.
