### ISSUE TITLE
[Question] Reactions with explicit atoms 

### ISSUE THREAD

**Issue by ohyh** [mlund/faunus#273]
Dear Faunus team,

I'd like to study a system that a chemical reaction (A + B -> C) occurs only desired region, for example, 0 < z < h. To build MC system like that, I isolate the explicit atoms (A) at z < 0 of the simulation box by using `customexternal`. And I confined atom B at the region of -h < z < h, also by using `customexternal`. 

Unfortunately, I learned that that only 2 explicit atoms are allowed from the error message: `Bad definition: Only 2 explicit atoms per reaction!`. I also consider constructing MC system by using implicit atoms. But I couldn't constraint implicit atoms at desired region of the simulation box, z < 0. 

I tried to assemble functions that are already implemented in the current version of Faunus to build my system, but failed. Would it require extensive coding to introduce some functionality like specify region in simulation box that 1) implicit atoms could exist, or 2) reaction could occur? Just like imposing `customexternal`, I'd like to used if loop on the reaction list section. 

I always appreciate your effort and kindness. 

Sincerely yours,
A user.

**Comment by mlund** [comment]
It's not possible to impose geometric restrictions on reactions, but you can rightly use an external potential to exclude reactants and/or products from specific regions. The 2-atom limit applies only to molecules with `atomic=True`, but you could instead define all your atoms as molecules with only _one_ atom and with `atomic=False`. For such non-atomic molecules, there's no limitation on the number of species in reactions. 

Have a look at the calciumhydroxide example; there're two versions, one using atomic groups and another using one-atom groups. We might need to explain this better in the manual, but the `atomic` keyword is mostly for optimisations and you can achieve the same functionality using molecular groups with just one atom. For this, please use the master branch as we made fixes relating to this not long ago (#267)

Btw. on point 1) above, did you mean _explicit_ and not _implicit_?

**Comment by ohyh** [comment]
Thanks for the guidance. I took a look at the examples, but I need explicit description of the product molecules. For question 1), I meant implicit. If I couldn't specify that implicit atoms might distributed, region specific reaction constant (`lnk` or `pk`) would solve all of my problem, for example, `lnk = 1000` for (-h < z) and lnk = 0.001 for (-h > z). 

Here is the description on the system that I want to build. I'm trying to build a polymer chain with implicit membrane (-h < z < h). At the beginning of the simulation, I'd like to define all of the monomers of the chain as hydrophobic (charge neutral) ones, so the chain could remains inside of the membrane. Some of the monomers might exposed to the one side of the membrane (z < -h), chemical reaction occurs and the monomer type changes to charged one, so it cannot go back into the membrane. Neighboring monomers getting more easier to be exposed, so next reaction could occur more easily. As serial reactions, all of the monomers are charged, so the polymer chain finally get out of the membrane and freely diffuse in the cytosolic region, just like ratchet mechanism. I'd like to design the chemical reaction on the monomer occurs only one side of the system, z < -h. Either implicit or explicit solvent design would work for me, as long as I could design the polymer chain explicitly. 

I appreciate your guidance and kindness.

**Comment by mlund** [comment]
Thanks for the explanation; I'll read at carefully later today. Let's also ping @gitesei who might have ideas.

**Comment by mlund** [comment]
Could a solution be that you impose an external potential on charges when they are inside the membrane, i.e. 0 when outside and infinity when inside? In `externalpotential` you have access to `q` and `z`, and in this way the reaction charged->uncharged never occurs for monomers outside.
You can then start your simulation in the fully neutral state and inside and the polymers will eventually end up on the outside. For this you'll likely need to trigger an atomic swap move as illustrated in the `phosphate` example.

**Comment by ohyh** [comment]
I appreciate the idea. You meant `customexternal`, not `externalpotential`, right? I think I could accomplish my goal by using the idea. Your idea could work because any chemical reaction that produce charged product can not be occur in the region of infinite surrounding charge? Hope I understand properly. 

I'd like to ask a technical questions. How could I impose infinite charge on desired region? In the manual `customexternal` could be defined as number (ex, z + 1000), not like full equation (q = inf).

**Comment by mlund** [comment]
Sorry, I meant `customexternal`. Yes, no charge would end up in the membrane region if you use something like this:

``` yaml
customexternal:
    constants: {membrane_width: 15} # membrane width in Angstrom
    function: >
        if ( abs(z) < membrane_width  )
            abs(q) * 1000; # large electric potential on charges
        else
            0;
```

**Comment by ohyh** [comment]
Dear @mlund, I successfully control the region-specific chemical reaction. Thanks for the great idea!

**Comment by mlund** [comment]
Great! Closing this; feel free to re-open if needed.
