### ISSUE TITLE
[Question] Simulation details that couldn't be found in the manual

### ISSUE THREAD

**Issue by ohyh** [mlund/faunus#274]
Dear Faunus team,

I have some questions on some simulation details that I couldn't find from the manual. 

1) `macro`, `micro`
In the manual, the number of outer and inner MC steps are defined by `macro` and `micro`, respectively. What is the exact difference between these parameter? Specific MC moves are only applied, for example `micro` move?

2) Potential form of `slit` simulation box.
What type of potential is applied to the `slit` geometry? I suspect that the upper and lower bound of the `slit` box might be charged. I notice that there are peaks of density profile of the charged molecules near the surface, but cannot be sure. It is not critical for my research, but would it be possible for make the wall interact with all of the particles in the system via WCA potential? 

3) Using multiple cores to run faunus
I put `export OMP_NUM_THREADS=4` on my bash environment file and run the Faunus, but fail to run it with 4 cores. I also tried bash script as follows, but also failed. I installed Faunus via miniconda. Do you have some idea what should I check for running multi-core simulation?
```
#!/bin/bash -l 
export OMP_NUM_THREADS=4
faunus -i in.json
```

As always, I appreciate your consideration.

Sincerely,
A user

**Comment by mlund** [comment]
Thanks for the input; it's very useful for improving faunus and particular the documentation (or lack thereof!).
1. We discussed this just last week, Iet's ping @rc83. Indeed this is undocumented, and currently the only difference is that analysis is saved to disk every macro step. The total number of MC steps is micro*macro.
2. `slit` is like `cuboid` but there's no PBC in the z direction. Particles are never allowed outside the box in any container (infinite potential).
3. Again you've found lack of documentation. Currently OpenMP applies only to certain analysis routines and will generally not affect MC simulation speed. We're working on this and it can be hacked in for specific use-cases. If your system equilibrates fast, I can recommend to make multiple runs with different random seeds for now.

Checklist for a pull request to fix this:
- [ ] document micro/macro keywords in `topology.md`
- [ ] document openmp
- [ ] document that particles cannot fall outside the container
