### ISSUE TITLE
Langevin dynamics implementation

### ISSUE THREAD

**Issue by SHervoe-Hansen** [mlund/faunus#282]
The implementation of Langevin dynamics in Faunus for a Lennard-Jones fluid/gas is well underway in my fork of <a href="https://github.com/SHervoe-Hansen/faunus/tree/forcemove_ld">Faunus</a>. Checklist which should preferably be handled as separate PRs:
- [x] Working example of LJ system
- [ ] Unit testing
  - simple LJ system. RDF, temperature, avg. kinetic and potential energy? Compare w. MC
  - harmonic oscillator?
- [ ] Force calculation implementation:
  - #284: Reciprocal ewald space
  - #283: Bonded interactions (harmonic, torsion, dihedrals -- see [OpenMM implementation](https://github.com/openmm/openmm/blob/master/platforms/reference/src/ReferenceKernels.cpp)) and also Allen+Tildesley, Appendix C
  - `FunctorPotential` for combined potentials
  - Anisotropic non-bonded interactions?
  - See Allen and Tildesley's Appendix C as well as their [Github rep](/Allen-Tildesley) with examples of force calculations (ewald, angles, dipoles etc.)
- [ ] Error handling
  - [ ] Gracefully exit from explosion (closes #305)
- [ ] Documentation (`moves.md`)
- [ ] An initialisation scheme for simulation of liquids (slow heating, minimisation using 0 K Monte Carlo).
- [ ] Improved control over MD/MC switching.
- [ ] Parallel scheme for force calculation in `Nonbonded` class (OMP pragmas?)

**Comment by himalayanpride** [comment]
Is it possible for me to get the beta version of the code where you have implemented langevin dynamics? I want to test CG martini system ( I don't have any angle/dihedral terms in the system). 
Thanks,
