### ISSUE TITLE
[question] Z position of Gouy Chapman function

### ISSUE THREAD

**Issue by ohyh** [mlund/faunus#294]
Dear Faunus Team,

I would like to use `customexternal` with `function= Gouy Chapman`. I found that reference plane is fixed at the minimum z-value of the simulation container. Implicit membrane with two Gouy Chapman plane is my target system. Would you guide me how to manipulate `function= Gouy Chapman`? I hope I could access more variables for the function. 

As always, thanks for your considerations. 

Sincerely, an user

**Comment by ohyh** [comment]
Dear Team, 

I think I could handle my situation, if I do not use `function= Gouy Chapman` and manually build Gouy Chapman by using `customexternal`. I think it is OK to close my question. 

Thanks!

**Comment by mlund** [comment]
Hi! The GC theory is valid for one plane only, i.e. it's the solution to the Poisson-Boltzmann eq. for a single, infinitely large plane. For two planes I don't think there an analytical expression, but would need to be solved numerically. I don't think it would be difficult to do this and add it as a splined external potential. Let us know if you need help.
