### ISSUE TITLE
yason.py converting to string instead of number for variable substitution

### ISSUE THREAD

**Issue by himalayanpride** [mlund/faunus#306]
While trying to generate .json with latest yason.py, I got error and when I compared the files generated from older version of  yason.py and the latest one; I find some difference. See the output from the latest yason.py.

{% set pH =  7 %}
atomlist:
    - H+:   { implicit: True, activity: {{ 10**(-pH) }} }

the .json output is:
      "H+": {
                   "implicit": true,
                   "activity": **"1e-07"**
               }

where the number are generated as strings (within quotation marks). 

The older version of yason.py works fine; which outputs number as expected.

**Comment by mlund** [comment]
Hmm, I it seems to do with [this](https://stackoverflow.com/questions/30458977/yaml-loads-5e-6-as-string-and-not-a-number) and possibly related to the version the yaml parser (ruamel) or jinja2. Will need to investigate. No changes has been made to the `yason.py` script as far as I recall.

**Comment by mlund** [comment]
The problem is that `1e-07` is passed as a string while `1.0e-7` is a number. You could use an ugly hack such as `{{ 10**(-pH + 0.0000001) }}` but this is of course not a permanent solution.

**Comment by mlund** [comment]
Could you try to install the `ruamel_yaml` package? On my system this works, whereas `yaml` doesn't. According to above link`yaml` has a bug that incorrectly pass the number as a string.

**Comment by himalayanpride** [comment]
Seem like it is not due to the yason.py. I have two versions installed (one in conda environment and one locally). I copied the yason.py from conda (which worked in conda environment) and tried with that in my local folder and it still generate string. That means, it has to do with the yaml package as you mentioned. I will try installing `ruamel_yaml` and see if it solves the error.

**Comment by mlund** [comment]
any luck with `ruamel_yaml`?

**Comment by himalayanpride** [comment]
Sorry for the late reply. Now after installing `ruamel_yaml`, I don't see the same error.
