### ISSUE TITLE
Current CI run failures

### ISSUE THREAD

**Issue by mbargull** [mlund/faunus#436]
I just checked back to see if my changes from gh-435 worked as expected.
I noticed the CI fails with:
```
[ 35%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/spdlog.cpp.o
In file included from /home/runner/work/faunus/faunus/build/_deps/spdlog-src/src/spdlog.cpp:8:
In file included from /home/runner/work/faunus/faunus/build/_deps/spdlog-src/include/spdlog/spdlog-inl.h:7:
In file included from /home/runner/work/faunus/faunus/build/_deps/spdlog-src/include/spdlog/spdlog.h:12:
In file included from /home/runner/work/faunus/faunus/build/_deps/spdlog-src/include/spdlog/common.h:10:
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/chrono:2320:48: error: call to consteval function 'std::chrono::hh_mm_ss::_S_fractional_width' is not a constant expression
        static constexpr unsigned fractional_width = {_S_fractional_width()};
                                                      ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/chrono:2320:48: note: undefined function '_S_fractional_width' cannot be used in a constant expression
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/chrono:2275:2: note: declared here
        _S_fractional_width()
        ^
1 error generated.
```
This is likely an interaction with an older `clang++` selecting `libstdc++ 13`.
There are multiple ways to tackle this:
- instruct `clang++` to use another (older, installed) `libstdc++` (possibly via `-stdlibc++-isystem=<path>` or rather`--gcc-toolchain=<path>`; haven't checked this)
- instruct `clang++` to use `libc++` (if that is really desired); (`-stdlib=c++`)
- install a newer Clang version

Cheers

**Comment by mlund** [comment]
Thanks for investigating - I'm pretty sure it's due to this regression https://github.com/actions/runner-images/issues/8659 at Github. I was hoping to avoid a local fix, but it might take a while before the runner is fixed.

**Comment by mlund** [comment]
Using `-stdlib=c++` which the initial issue, but created another:
https://github.com/mlund/faunus/actions/runs/7002102999/job/19045248972

**Comment by mbargull** [comment]
The failure comes from (old?) `ld`. You may want to add `-fuse-ld=lld` to `LDFLAGS` to use LLVM's linker.

**Comment by mlund** [comment]
Thanks, the `LDFLAGS` seemed to help, but now the complaint is from the C compiler: https://github.com/mlund/faunus/actions/runs/7043378817/job/19169047119
