### ISSUE TITLE
xtc output is not correct

### ISSUE THREAD

**Issue by robertvacha** [mlund/faunus#76]
when pqr and xtc files are printed after move they do not correspond to each other. When first particle moves, in xtc it is movement of second particle.

**Comment by robertvacha** [comment]
it correct in commit 03a8d514333db5bdad25077ac1310cb706fc4b5b
 Added "keeppos" when inserting molecules

**Comment by robertvacha** [comment]
It probably has something to do with groups, because when I have 5 or more protein in the specific the simulation - it crashes with segmentation fault, but it runs fine with 4 or less proteins (each protein has different group). When I print pqr and do not print xtc it works fine.

**Comment by mlund** [comment]
Could you upload a minimal example that reproduces this? That is `.cpp` and input files.

**Comment by robertvacha** [comment]
﻿
[Archive.zip](https://github.com/mlund/faunus/files/558874/Archive.zip)

**Comment by robertvacha** [comment]
[Archive-2.zip](https://github.com/mlund/faunus/files/558879/Archive-2.zip)

**Comment by mlund** [comment]
Do you by "particle" mean "molecule" as in a full protein? I cannot reproduce segfault (using clang++) with five proteins.

**Comment by mlund** [comment]
I reduced to proteins to 10 amino acids and increased the steps significantly. Can you reproduce with attached files?

[minimal.zip](https://github.com/mlund/faunus/files/560622/minimal.zip)

**Comment by robertvacha** [comment]
Your version works. I additionally tested my version on mac laptop and it works there, but still gives segmentation fault on linux desktop or clusters :(

Anyways, the second problem is consistent also on my mac laptop. That is attached simulation, where I move only one particle in the system and that is "flexible” part = 0th particle. But when I load xtc it is not 0th particle that moves but the first particle.

**Comment by mlund** [comment]
I still cannot reproduce the segfault on linux (clang++, gcc5). Could you run it through a debugger, i.e. `$ gdb ./capsidpent` and post the output here?

**Comment by robertvacha** [comment]
It crashes on the first attempt to write an xtc file. Below I copy paste 
output of gdb

$ gdb ./capsidpent
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later 
<http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./capsidpent...done.
(gdb) run
Starting program: /home/robert/Sim/Virus/SBPV/full/TIT/test2/capsidpent
.......................................................................
   Welcome to FAUNUS - A Framework for Molecule Simulation.
   Copyright (C) 2002-2015 Mikael Lund

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

    ___________                               _________
    \_   _____/_____    __ __   ____   __ __ /   _____/
     |    __)  \__  \  |  |  \ /    \ |  |  \\_____  \
     |     \    / __ \_|  |  /|   |  \|  |  //        \
     \___  /   (____  /|____/ |___|  /|____//_______  /
         \/         \/             \/               \/

   Developed by:
     Mikael Lund, Björn Persson, Martin Trulsson,
     Ondřej Maršálek, Christophe Labbez, Andre Teixeira,
     Anıl Kurut, Chris Evers, Robert Vácha, Axel Thuresson,
     Björn Stenqvist, João Henriques, Alexei Abrikossov,
     Giulio Tesei, Lukáš Sukeník.

   References:
     http://doi.org/nvn (2013)
     http://doi.org/dfqgch (2008)

   Library build details:
     Compiled on Nov  1 2016 08:39:36
     Git commit 3c823c8 (2016-09-01 11:57:47 +0200)
***********************************************************************
Inputs read
Space set
# Reading process H-Arg ... OK!
# Reading process H-Asp ... OK!
# Reading process H-Ctr ... OK!
# Reading process H-Cys ... OK!
# Reading process H-Glu ... OK!
# Reading process H-His ... OK!
# Reading process H-Lys ... OK!
# Reading process H-Ntr ... OK!
# Reading process H-Tyr ... OK!
# Reading process K1 ... OK!
# Reading process K2 ... OK!
# Reading process K3 ... OK!
Potential specified
# Reading process H-Arg ... OK!
# Reading process H-Asp ... OK!
# Reading process H-Ctr ... OK!
# Reading process H-Cys ... OK!
# Reading process H-Glu ... OK!
# Reading process H-His ... OK!
# Reading process H-Lys ... OK!
# Reading process H-Ntr ... OK!
# Reading process H-Tyr ... OK!
# Reading process K1 ... OK!
# Reading process K2 ... OK!
# Reading process K3 ... OK!
Reading space state file 'proteins-state'. OK!
   Read 24075 particle(s).
   Read 5 group(s).
   Restoring random number generator state.

  .................
   Atom Properties
  *****************
   Number of entries:       46
   Element info:
     unk   ALA   ARG   ASN   ASP   BPTI  CTR   CYS   Ca    Cl
     GLN   GLU   GLY   H2PO4 H3PO4 HARG  HASP  HCTR  HCYS  HGLU
     HHIS  HIS   HLYS  HNTR  HPO4  HTYR  ILE   LEU   LYS   MET
     MYRC  MYRT  NTR   Na    PHE   PO4   PRO   SER   THR   TRP
     TYR   VAL   W711  W712  W713  W714

  ...............................
   Simulation Space and Geometry
  *******************************
   Boundary                 Cuboid
   Volume                   1e+09 Å³ = 1e+06 nm³ = 1e-18 liters
   Sidelengths              1000 1000 1000 (Å)
   Scale directions         XYZ
   Number of particles      24075
   Electroneutrality        NO! -243
   System sanity check      Passed
   Number of molecule types 5
   Groups:
     1     [0-4814]         protein1
     2     [4815-9629]      protein2
     3     [9630-14444]     protein3
     4     [14445-19259]    protein4
     5     [19260-24074]    protein5

  ..............................................................
   Energy: Nonbonded N² - Debye-Huckel+Lennard-Jones (default)
  **************************************************************
   Temperature              298 K
   Dielectric constant      78.7
   T∂ϵ/ϵ∂T                  -1.39344
   Bjerrum length           7.12501 Å
   Ionic strength           0.0997982 mol/l
   Debye length, 1/κ        9.63942 9.63942 Å
   Debye length, 1/κ        -nan Å (counter ions)
   Debye length, 1/κ        9.62969 Å (salt)
   ϵ(LJ)                    0.05 kT = 0.123886 kJ/mol

  ..................................
   Energy: Equilibrium State Energy
  **********************************
   Number of sites          6375
   Processes:

      AX <-> A         pKd      pX     pAX      pA N     ⟨Z⟩
----------------------------------------------------------------------
    HARG <-> ARG        12     6.5      -0     5.5    1250
    HASP <-> ASP         4     6.5      -0    -2.5    1350
    HCTR <-> CTR       2.6     6.5      -0    -3.9      75
    HCYS <-> CYS      10.8     6.5      -0     4.3     125
    HGLU <-> GLU       4.4     6.5      -0    -2.1    1150
    HHIS <-> HIS       6.3     6.5      -0    -0.2     375
    HLYS <-> LYS      10.4     6.5      -0     3.9     825
    HNTR <-> NTR       7.5     6.5      -0       1      75
    HTYR <-> TYR       9.6     6.5      -0     3.1    1150
   H3PO4 <-> H2PO4    2.12     6.5      -0   -4.38       0
   H2PO4 <-> HPO4     7.21     6.5   -4.38   -3.67       0
    HPO4 <-> PO4     12.67     6.5   -3.67     2.5       0

  .........................
   System Energy and Drift
  *************************
   Average                  1.56428e+10 kT, σ=0
   Initial energy           1.56428e+10 kT
   Initial + changes        1.56428e+10 kT
   Total energy drift       0 kT (0﹪)

  .......................
   MC Simulation Begins!
  ***********************
Writing to file 'proteins-confinit.pqr'. OK!
   Writing space state file 'proteins-state'. OK!
   Steps:    1 / 2           Macrosteps/min: 0       ETA: Tue Nov 1 
17:58:08 2016

Program received signal SIGSEGV, Segmentation fault.
0x00000000004f435d in Faunus::FormatXTC::save<Faunus::PointParticle, 
Eigen::aligned_allocator<Faunus::PointParticle>, Faunus::Group> 
(this=0x7fffffffcaf0, file="proteinstraj.xtc", p=std::vector of length 
24075, capacity 38520 = {...}, g=...)
     at /home/robert/Sim/faunus-new/faunus/include/faunus/io.h:641
641                   x[i][0] = p[j].x()*0.1 + xdbox[0][0]*0.5; // AA->nm
(gdb

**Comment by mlund** [comment]
Thanks! I found a bug when resize an empty group which may also be behind your out of sync particle index. Could you check if this work in the latest commit (b9bb230) ?

**Comment by robertvacha** [comment]
It works, THX!
It fixed both segmentation fault and wrong particle movement in xtc.
Rob
