### ISSUE TITLE
Default value can override value from JSON config object

### ISSUE THREAD

**Issue by Zweedeend** [mlund/faunus#78]
I think the way default values are provided may be incorrect. Consider this code:

```c++
  inline UnitTest::UnitTest(Tmjson &j) {
    cnt=0;
    auto _j = j["system"]["unittest"];
    file    = _j["testfile"] | string();
    stable  = _j["stable"] | true;  // <-- This always evaluates to true
    include( file );
  }
```

A better way would be:

```c++
    stable  = _j.value("stable", true);
```
Which works as expected: look up the value, or return the default when it can not be found.

------------

I guess this replacement is only _necessary_ if:
- the value provided by the config *could* be falsey (`0`, `nullptr`, `false` or `""`)
- the default value is truthy (ie not falsey)

**Comment by mlund** [comment]
The | operator is overloaded for JSON objects in Faunus - see `json.h:266`. The `value()` function in the JSON library was not initially there, hence this fix which is obviously not needed anymore.
