### ISSUE TITLE
Make sure to tag commits used in faunus-notebooks

### ISSUE THREAD

**Issue by Zweedeend** [mlund/faunus#82]
I noticed a commit that was used in a faunus-notebook, but was "orphaned", i.e. it was no longer part of the history of any tag or branch. The result is that this commit cannot be fetched by anyone who doesn't already have it. 

I think this wasn't noticed before because the offending `git checkout` was one line of a bash script. If a command fails, bash silently ignores the error and moves to the next line. (See my [comment on the faunus-notebooks repository](f9e6f969c0a82e75ab6facaf81b7bc6ce639a2ce))

The solution would be to create a tag for a commit if it is used in a notebook. Tags are very lightweight: it is a 40 bytes file which only content is a commit hash.

**Comment by mlund** [comment]
Noted, thanks!
