### ISSUE TITLE
Jupyter notebook for Charge & Second Virial Coefficient (Salt & pH)

### ISSUE THREAD

**Issue by nwahome** [mlund/faunus#97]
Would it be possible to get a Jupyter notebook (& the environment it was set up in), to calculate charge and second virial coefficient over salt & pH space? Similar to Figure 2 & 3 in your Faraday Discussions paper?

Kurut, Anıl, and Mikael Lund. "Solution electrostatics beyond pH: a coarse grained approach to ion specific interactions between macromolecules." Faraday discussions 160 (2013): 271-278.

**Comment by mlund** [comment]
We do not have a notebook for the 2013 paper, but for setting u a twobody simulation in a cylindrical geometry, see i.e. the twobody example in the separate repository:

https://github.com/mlund/faunus-notebooks
